import "server-only";

import { adminStorage } from "@/lib/firebase/admin";

// Upload the "15 Years of Geekdom" photos to this Storage folder — they appear
// on /15-years automatically. Kept behind the deny-all rules; the page serves
// them via short-lived signed URLs generated by the Admin SDK.
const PREFIX = "15-years/";
const IMAGE_EXT = /\.(jpe?g|png|webp|avif|gif)$/i;
const SIGN_TTL_MS = 7 * 24 * 60 * 60 * 1000; // 7 days

export interface GalleryImage {
  name: string;
  url: string;
}

export async function getGalleryImages(): Promise<GalleryImage[]> {
  try {
    const [files] = await adminStorage.bucket().getFiles({ prefix: PREFIX });
    const images = files.filter((f) => IMAGE_EXT.test(f.name));

    const signed = await Promise.all(
      images.map(async (f) => {
        const [url] = await f.getSignedUrl({
          action: "read",
          expires: Date.now() + SIGN_TTL_MS,
        });
        return { name: f.name.slice(PREFIX.length), url };
      }),
    );

    return signed.sort((a, b) => a.name.localeCompare(b.name));
  } catch (err) {
    console.error("Gallery listing failed:", err);
    return [];
  }
}
